In [1]:
import pandas as pd

In [3]:
# read_excel is used to read the data or  load the excel data
df = pd.read_excel(r'C:\Users\Naveen\Downloads\data sets\Attribute DataSet.xlsx')

In [4]:
df

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type,Recommendation
0,1006032852,Sexy,Low,4.6,M,Summer,o-neck,sleevless,empire,NaN,chiffon,ruffles,animal,1
1,1212192089,Casual,Low,0.0,L,Summer,o-neck,Petal,natural,microfiber,NaN,ruffles,animal,0
2,1190380701,vintage,High,0.0,L,Automn,o-neck,full,natural,polyster,NaN,NaN,print,0
3,966005983,Brief,Average,4.6,L,Spring,o-neck,full,natural,silk,chiffon,embroidary,print,1
4,876339541,cute,Low,4.5,M,Summer,o-neck,butterfly,natural,chiffonfabric,chiffon,bow,dot,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,713391965,Casual,Low,4.7,M,Spring,o-neck,full,natural,polyster,NaN,NaN,solid,1
496,722565148,Sexy,Low,4.3,free,Summer,o-neck,full,empire,cotton,NaN,NaN,NaN,0
497,532874347,Casual,Average,4.7,M,Summer,v-neck,full,empire,cotton,NaN,lace,solid,1
498,655464934,Casual,Average,4.6,L,winter,boat-neck,sleevless,empire,silk,broadcloth,applique,print,1
499,919930954,Casual,Low,4.4,free,Summer,v-neck,short,empire,cotton,Corduroy,lace,solid,0

In [5]:
df.head()

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type,Recommendation
0,1006032852,Sexy,Low,4.6,M,Summer,o-neck,sleevless,empire,NaN,chiffon,ruffles,animal,1
1,1212192089,Casual,Low,0.0,L,Summer,o-neck,Petal,natural,microfiber,NaN,ruffles,animal,0
2,1190380701,vintage,High,0.0,L,Automn,o-neck,full,natural,polyster,NaN,NaN,print,0
3,966005983,Brief,Average,4.6,L,Spring,o-neck,full,natural,silk,chiffon,embroidary,print,1
4,876339541,cute,Low,4.5,M,Summer,o-neck,butterfly,natural,chiffonfabric,chiffon,bow,dot,0

In [6]:
df.tail()

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type,Recommendation
495,713391965,Casual,Low,4.7,M,Spring,o-neck,full,natural,polyster,NaN,NaN,solid,1
496,722565148,Sexy,Low,4.3,free,Summer,o-neck,full,empire,cotton,NaN,NaN,NaN,0
497,532874347,Casual,Average,4.7,M,Summer,v-neck,full,empire,cotton,NaN,lace,solid,1
498,655464934,Casual,Average,4.6,L,winter,boat-neck,sleevless,empire,silk,broadcloth,applique,print,1
499,919930954,Casual,Low,4.4,free,Summer,v-neck,short,empire,cotton,Corduroy,lace,solid,0

In [10]:
pd.read_csv(r'C:\Users\Naveen\Downloads\data sets\haberman.csv',header = None,)

      0   1  2  3
0    30  64  1  1
1    30  62  3  1
2    30  65  0  1
3    31  59  2  1
4    31  65  4  1
..   ..  .. .. ..
301  75  62  1  1
302  76  67  0  1
303  77  65  3  1
304  78  65  1  2
305  83  58  2  2

[306 rows x 4 columns]

In [12]:

pd.read_csv(r'C:\Users\Naveen\Downloads\data sets\haberman.csv',header = None)

      0   1  2  3
0    30  64  1  1
1    30  62  3  1
2    30  65  0  1
3    31  59  2  1
4    31  65  4  1
..   ..  .. .. ..
301  75  62  1  1
302  76  67  0  1
303  77  65  3  1
304  78  65  1  2
305  83  58  2  2

[306 rows x 4 columns]

In [13]:
# here we are using names = ['Age', "Patient's year of operation ","Number of positive","Survival status"]
pd.read_csv(r'C:\Users\Naveen\Downloads\data sets\haberman.csv',header = None,names = ['Age ', "Patient's year of operation ","Number of positive","Survival status"])

     Age   Patient's year of operation   Number of positive  Survival status
0      30                            64                   1                1
1      30                            62                   3                1
2      30                            65                   0                1
3      31                            59                   2                1
4      31                            65                   4                1
..    ...                           ...                 ...              ...
301    75                            62                   1                1
302    76                            67                   0                1
303    77                            65                   3                1
304    78                            65                   1                2
305    83                            58                   2                2

[306 rows x 4 columns]

In [15]:
# here we performed the , to @
pd.read_csv(r'C:\Users\Naveen\Downloads\data sets\haberman1.csv')

      30@64@1@1
0     30@62@3@1
1     30@65@0@1
2     31@59@2@1
3     31@65@4@1
4    33@58@10@1
..          ...
912   75@62@1@1
913   76@67@0@1
914   77@65@3@1
915   78@65@1@2
916   83@58@2@2

[917 rows x 1 columns]

In [16]:
# here delimeter @ and performing seperations
pd.read_csv(r'C:\Users\Naveen\Downloads\data sets\haberman1.csv',sep= '@')

     30  64   1  1.1
0    30  62   3    1
1    30  65   0    1
2    31  59   2    1
3    31  65   4    1
4    33  58  10    1
..   ..  ..  ..  ...
912  75  62   1    1
913  76  67   0    1
914  77  65   3    1
915  78  65   1    2
916  83  58   2    2

[917 rows x 4 columns]

In [18]:
# we can read the csv data from github repo by clicking raw and coping the raw url and past init we can able to read github data as well.
pd.read_csv(r'https://raw.githubusercontent.com/selva86/datasets/master/Smarket.csv')

      Year   Lag1   Lag2   Lag3   Lag4   Lag5   Volume  Today Direction
0     2001  0.381 -0.192 -2.624 -1.055  5.010  1.19130  0.959        Up
1     2001  0.959  0.381 -0.192 -2.624 -1.055  1.29650  1.032        Up
2     2001  1.032  0.959  0.381 -0.192 -2.624  1.41120 -0.623      Down
3     2001 -0.623  1.032  0.959  0.381 -0.192  1.27600  0.614        Up
4     2001  0.614 -0.623  1.032  0.959  0.381  1.20570  0.213        Up
...    ...    ...    ...    ...    ...    ...      ...    ...       ...
1245  2005  0.422  0.252 -0.024 -0.584 -0.285  1.88850  0.043        Up
1246  2005  0.043  0.422  0.252 -0.024 -0.584  1.28581 -0.955      Down
1247  2005 -0.955  0.043  0.422  0.252 -0.024  1.54047  0.130        Up
1248  2005  0.130 -0.955  0.043  0.422  0.252  1.42236 -0.298      Down
1249  2005 -0.298  0.130 -0.955  0.043  0.422  1.38254 -0.489      Down

[1250 rows x 9 columns]

# here we are reading data from website using read_html 
# we can read the data only avaliable in tabular formate

In [20]:
pd.read_html(r'https://www.basketball-reference.com/leagues/NBA_2015_totals.html')

[      Rk          Player Pos Age   Tm   G  GS    MP   FG  FGA  ...   FT%  ORB  \
 0      1      Quincy Acy  PF  24  NYK  68  22  1287  152  331  ...  .784   79
 1      2    Jordan Adams  SG  20  MEM  30   0   248   35   86  ...  .609    9
 2      3    Steven Adams   C  21  OKC  70  67  1771  217  399  ...  .502  199
 3      4     Jeff Adrien  PF  28  MIN  17   0   215   19   44  ...  .579   23
 4      5   Arron Afflalo  SG  29  TOT  78  72  2502  375  884  ...  .843   27
 ..   ...             ...  ..  ..  ...  ..  ..   ...  ...  ...  ...   ...  ...
 670  490  Thaddeus Young  PF  26  TOT  76  68  2434  451  968  ...  .655  127
 671  490  Thaddeus Young  PF  26  MIN  48  48  1605  289  641  ...  .682   75
 672  490  Thaddeus Young  PF  26  BRK  28  20   829  162  327  ...  .606   52
 673  491     Cody Zeller   C  22  CHO  62  45  1487  172  373  ...  .774   97
 674  492    Tyler Zeller   C  25  BOS  82  59  1731  340  619  ...  .823  146

      DRB  TRB  AST  STL BLK  TOV   PF   PTS
 0    222  301   68   27  22   60  147   398
 1     19   28   16   16   7   14   24    94
 2    324  523   66   38  86   99  222   537
 3     54   77   15    4   9    9   30    60
 4    220  247  129   41   7  116  167  1035
 ..   ...  ...  ...  ...  ..  ...  ...   ...
 670  284  411  173  124  25  117  171  1071
 671  170  245  135   86  17   75  115   685
 672  114  166   38   38   8   42   56   386
 673  265  362  100   34  49   62  156   472
 674  319  465  113   18  52   76  205   833

 [675 rows x 30 columns]]

In [21]:
# here we are reading data from website using read_html
a = pd.read_html(r'https://www.basketball-reference.com/leagues/NBA_2015_totals.html')

In [22]:
type(a)

list

In [23]:
len(a)

1

In [24]:
a[0]

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,Quincy Acy,PF,24,NYK,68,22,1287,152,331,...,.784,79,222,301,68,27,22,60,147,398
1,2,Jordan Adams,SG,20,MEM,30,0,248,35,86,...,.609,9,19,28,16,16,7,14,24,94
2,3,Steven Adams,C,21,OKC,70,67,1771,217,399,...,.502,199,324,523,66,38,86,99,222,537
3,4,Jeff Adrien,PF,28,MIN,17,0,215,19,44,...,.579,23,54,77,15,4,9,9,30,60
4,5,Arron Afflalo,SG,29,TOT,78,72,2502,375,884,...,.843,27,220,247,129,41,7,116,167,1035
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
670,490,Thaddeus Young,PF,26,TOT,76,68,2434,451,968,...,.655,127,284,411,173,124,25,117,171,1071
671,490,Thaddeus Young,PF,26,MIN,48,48,1605,289,641,...,.682,75,170,245,135,86,17,75,115,685
672,490,Thaddeus Young,PF,26,BRK,28,20,829,162,327,...,.606,52,114,166,38,38,8,42,56,386
673,491,Cody Zeller,C,22,CHO,62,45,1487,172,373,...,.774,97,265,362,100,34,49,62,156,472
674,492,Tyler Zeller,C,25,BOS,82,59,1731,340,619,...,.823,146,319,465,113,18,52,76,205,833

In [26]:
a[0]

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,Quincy Acy,PF,24,NYK,68,22,1287,152,331,...,.784,79,222,301,68,27,22,60,147,398
1,2,Jordan Adams,SG,20,MEM,30,0,248,35,86,...,.609,9,19,28,16,16,7,14,24,94
2,3,Steven Adams,C,21,OKC,70,67,1771,217,399,...,.502,199,324,523,66,38,86,99,222,537
3,4,Jeff Adrien,PF,28,MIN,17,0,215,19,44,...,.579,23,54,77,15,4,9,9,30,60
4,5,Arron Afflalo,SG,29,TOT,78,72,2502,375,884,...,.843,27,220,247,129,41,7,116,167,1035
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
670,490,Thaddeus Young,PF,26,TOT,76,68,2434,451,968,...,.655,127,284,411,173,124,25,117,171,1071
671,490,Thaddeus Young,PF,26,MIN,48,48,1605,289,641,...,.682,75,170,245,135,86,17,75,115,685
672,490,Thaddeus Young,PF,26,BRK,28,20,829,162,327,...,.606,52,114,166,38,38,8,42,56,386
673,491,Cody Zeller,C,22,CHO,62,45,1487,172,373,...,.774,97,265,362,100,34,49,62,156,472
674,492,Tyler Zeller,C,25,BOS,82,59,1731,340,619,...,.823,146,319,465,113,18,52,76,205,833

In [30]:
# we are performing the json viewer by read_json

js = pd.read_json(r'https://api.github.com/repos/pandas-dev/pandas/issues')

In [31]:
js

,url,repository_url,labels_url,comments_url,events_url,html_url,id,node_id,number,title,...,closed_at,author_association,active_lock_reason,draft,pull_request,body,reactions,timeline_url,performed_via_github_app,state_reason
0,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/54283,1825413996,PR_kwDOAA0YD85Wmfsw,54283,DOC: Remove roadmap.rst in favor of the websit...,...,NaT,MEMBER,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,https://pandas.pydata.org/about/roadmap.html s...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
1,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/54282,1825292403,PR_kwDOAA0YD85WmFeW,54282,DOC: Use more executed instead of static code ...,...,NaT,MEMBER,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [x] closes #45235 (Replace xxxx with the Git...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
2,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/54281,1825267527,PR_kwDOAA0YD85WmACd,54281,TYP: Add typing.overload signatures to DataFra...,...,NaT,NONE,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,This adds overloads so that a type checker can...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
3,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/54279,1824855992,PR_kwDOAA0YD85WklQM,54279,Added AWS_S3_HOST environment variable workaro...,...,NaT,NONE,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,â€¦ssue #26195\r\n\r\n- [ ] closes #xxxx (Replac...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
4,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/54278,1824850213,PR_kwDOAA0YD85Wkj_2,54278,DOC: Fixing EX01 - Added examples,...,NaT,MEMBER,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [x] All [code checks passed](https://pandas....,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
5,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/54275,1824182764,I_kwDOAA0YD85sutHs,54275,DEPR: deprecate the alias 'A' in favour of 'Y'...,...,NaT,CONTRIBUTOR,NaN,NaN,NaN,Context: we renamed `'M'` to `'ME' `for offset...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
6,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/54274,1823784409,I_kwDOAA0YD85stL3Z,54274,BUG: to_sql() insertion issue to Oracle DB,...,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
7,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/54273,1823542216,I_kwDOAA0YD85ssQvI,54273,BUG: When assigning values to a subset DataFra...,...,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
8,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/54272,1823411432,PR_kwDOAA0YD85WftTC,54272,Remove test_groupby_agg_extension (marked xfail),...,NaT,NONE,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,Remove special `test_groupby_agg_extension` in...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
9,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/54269,1822944464,PR_kwDOAA0YD85WeHr1,54269,Wrote test for Issue#29576 with resampling in ...,...,NaT,NONE,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [ ] closes #29576\r\n- [ ] Added test to `te...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
10,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/54268,1822819460,PR_kwDOAA0YD85Wdsiq,54268,DEPS: Update reprs with numpy NEP51 scalar repr,...,NaT,MEMBER,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,xref https://github.com/numpy/numpy/pull/22449,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
11,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/54265,1822123528,PR_kwDOAA0YD85WbWEx,54265,Modified doc/make.py to run sphinx-build -b li...,...,NaT,CONTRIBUTOR,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [x] xref #45409 (Replace xxxx with the GitHu...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
12,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/54264,1821921606,I_kwDOAA0YD85smFFG,54264,read_spss doens't return the metadata,...,NaT,NONE,NaN,NaN,NaN,### Feature Type\n\n- [ ] Adding new functiona...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
13,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/54263,1821847254,PR_kwDOAA0YD85WaaJD,54263,BUG: pivot_table mean of integer input casted ...,...,NaT,NONE,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [x] closes #16676\r\n- [x] [Tests added and ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
14,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/54261,1821405798,PR_kwDOAA0YD85WY-f5,54261,DEPR: fillna downcasting from object dtype,...,NaT,MEMBER,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [x] closes #11537 (Replace xxxx with the Git...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
15,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/54260,1821106348,PR_kwDOAA0YD85WX-Tj,54260,STYL: replace autotyping with ruff's ANN autof...,...,NaT,CONTRIBUTOR,NaN,1.0,{'url': 'https://api.github.com/repos/pandas-d...,ruff's ANN has many of the autofixes from auto...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
16,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/54259,1820820706,I_kwDOAA0YD85sh4Ti,54259,BUG: matplotlib backend issue when building do...,...,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
17,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/54258,1820713531,PR_kwDOAA0YD85WWoyq,54258,REF: de-duplicate ensure_np_dtype,...,NaT,MEMBER,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [ ] closes #xxxx (Replace xxxx with the GitH...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
18,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/54255,1820429668,I_kwDOAA0YD85sgY1k,54255,Gitpod is not allowing to push code to forked ...,...,NaT,CONTRIBUTOR,NaN,NaN,NaN,I'm having the following trouble using gitpod....,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
19,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/54252,1820310784,I_kwDOAA0YD85sf70A,54252,BUG: pandas coerces `np.longlong` to `np.int64`,...,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
20,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/54251,1820173891,I_kwDOAA0YD85sfaZD,54251,"BUG: `Series.astype(""object_"")` and `Series.as...",...,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\r\n\r\n- [X] I have ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
21,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/54250,1819948764,I_kwDOAA0YD85sejbc,54250,BUG: list output incorrectly reused when calli...,...,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
22,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/54249,1819714948,I_kwDOAA0YD85sdqWE,54249,BUG: joining empty frame to multiindex frame n...,...,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\r\n\r\n- [X] I have ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
23,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/54243,1818708139,PR_kwDOAA0YD85WPz-U,54243,"DOC Update Documentation in ""missing_data"" 54028",...,NaT,NONE,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [ ] closes #54028\r\nAdds reference notes fo...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
24,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/54238,1817960637,PR_kwDOAA0YD85WNQkp,54238,DEPR offsets: rename 'Y' to 'YE',...,NaT,CONTRIBUTOR,NaN,1.0,{'url': 'https://api.github.com/repos/pandas-d...,xref #52064,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
25,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/54237,1817743126,I_kwDOAA0YD85sWI8W,54237,PERF: Large row dataframe process groupby and ...,...,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
26,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/54235,1817198988,I_kwDOAA0YD85sUEGM,54235,"DEPR: Period, PeriodFoo",...,NaT,MEMBER,NaN,NaN,NaN,"This was discussed a few dev calls ago, merits...",{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
27,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/54234,1817186156,PR_kwDOAA0YD85WKuXC,54234,PERF: Implement groupby idxmax/idxmin in Cython,...,NaT,MEMBER,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [x] closes #10694 (Replace xxxx with the Git...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
28,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/54233,1817009075,I_kwDOAA0YD85sTVuz,54233,"BUG: ""table name"" form of `pd.read_sql()` doe...",...,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
29,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/54232,1816932794,PR_kwDOAA0YD85WJ9C5,54232,DOC: Imporve `json_normalize` record_prefix an...,...,NaT,CONTRIBUTOR,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [ ] closes #54121 (Replace xxxx with the Gi...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN

In [32]:
js.columns

Index(['url', 'repository_url', 'labels_url', 'comments_url', 'events_url',
       'html_url', 'id', 'node_id', 'number', 'title', 'user', 'labels',
       'state', 'locked', 'assignee', 'assignees', 'milestone', 'comments',
       'created_at', 'updated_at', 'closed_at', 'author_association',
       'active_lock_reason', 'draft', 'pull_request', 'body', 'reactions',
       'timeline_url', 'performed_via_github_app', 'state_reason'],
      dtype='object')

In [42]:
len('user')

4

In [38]:
js['user'][0]

{'login': 'mroeschke',
 'id': 10647082,
 'node_id': 'MDQ6VXNlcjEwNjQ3MDgy',
 'avatar_url': 'https://avatars.githubusercontent.com/u/10647082?v=4',
 'gravatar_id': '',
 'url': 'https://api.github.com/users/mroeschke',
 'html_url': 'https://github.com/mroeschke',
 'followers_url': 'https://api.github.com/users/mroeschke/followers',
 'following_url': 'https://api.github.com/users/mroeschke/following{/other_user}',
 'gists_url': 'https://api.github.com/users/mroeschke/gists{/gist_id}',
 'starred_url': 'https://api.github.com/users/mroeschke/starred{/owner}{/repo}',
 'subscriptions_url': 'https://api.github.com/users/mroeschke/subscriptions',
 'organizations_url': 'https://api.github.com/users/mroeschke/orgs',
 'repos_url': 'https://api.github.com/users/mroeschke/repos',
 'events_url': 'https://api.github.com/users/mroeschke/events{/privacy}',
 'received_events_url': 'https://api.github.com/users/mroeschke/received_events',
 'type': 'User',
 'site_admin': False}

In [43]:
js['user'][1]

{'login': 'mroeschke',
 'id': 10647082,
 'node_id': 'MDQ6VXNlcjEwNjQ3MDgy',
 'avatar_url': 'https://avatars.githubusercontent.com/u/10647082?v=4',
 'gravatar_id': '',
 'url': 'https://api.github.com/users/mroeschke',
 'html_url': 'https://github.com/mroeschke',
 'followers_url': 'https://api.github.com/users/mroeschke/followers',
 'following_url': 'https://api.github.com/users/mroeschke/following{/other_user}',
 'gists_url': 'https://api.github.com/users/mroeschke/gists{/gist_id}',
 'starred_url': 'https://api.github.com/users/mroeschke/starred{/owner}{/repo}',
 'subscriptions_url': 'https://api.github.com/users/mroeschke/subscriptions',
 'organizations_url': 'https://api.github.com/users/mroeschke/orgs',
 'repos_url': 'https://api.github.com/users/mroeschke/repos',
 'events_url': 'https://api.github.com/users/mroeschke/events{/privacy}',
 'received_events_url': 'https://api.github.com/users/mroeschke/received_events',
 'type': 'User',
 'site_admin': False}

In [44]:
js['user'][2]

{'login': 'rchen152',
 'id': 4142312,
 'node_id': 'MDQ6VXNlcjQxNDIzMTI=',
 'avatar_url': 'https://avatars.githubusercontent.com/u/4142312?v=4',
 'gravatar_id': '',
 'url': 'https://api.github.com/users/rchen152',
 'html_url': 'https://github.com/rchen152',
 'followers_url': 'https://api.github.com/users/rchen152/followers',
 'following_url': 'https://api.github.com/users/rchen152/following{/other_user}',
 'gists_url': 'https://api.github.com/users/rchen152/gists{/gist_id}',
 'starred_url': 'https://api.github.com/users/rchen152/starred{/owner}{/repo}',
 'subscriptions_url': 'https://api.github.com/users/rchen152/subscriptions',
 'organizations_url': 'https://api.github.com/users/rchen152/orgs',
 'repos_url': 'https://api.github.com/users/rchen152/repos',
 'events_url': 'https://api.github.com/users/rchen152/events{/privacy}',
 'received_events_url': 'https://api.github.com/users/rchen152/received_events',
 'type': 'User',
 'site_admin': False}

In [45]:
js['user'][3]

{'login': 'kvn4',
 'id': 55560840,
 'node_id': 'MDQ6VXNlcjU1NTYwODQw',
 'avatar_url': 'https://avatars.githubusercontent.com/u/55560840?v=4',
 'gravatar_id': '',
 'url': 'https://api.github.com/users/kvn4',
 'html_url': 'https://github.com/kvn4',
 'followers_url': 'https://api.github.com/users/kvn4/followers',
 'following_url': 'https://api.github.com/users/kvn4/following{/other_user}',
 'gists_url': 'https://api.github.com/users/kvn4/gists{/gist_id}',
 'starred_url': 'https://api.github.com/users/kvn4/starred{/owner}{/repo}',
 'subscriptions_url': 'https://api.github.com/users/kvn4/subscriptions',
 'organizations_url': 'https://api.github.com/users/kvn4/orgs',
 'repos_url': 'https://api.github.com/users/kvn4/repos',
 'events_url': 'https://api.github.com/users/kvn4/events{/privacy}',
 'received_events_url': 'https://api.github.com/users/kvn4/received_events',
 'type': 'User',
 'site_admin': False}

In [46]:
js['user'][4]

{'login': 'DeaMariaLeon',
 'id': 11835246,
 'node_id': 'MDQ6VXNlcjExODM1MjQ2',
 'avatar_url': 'https://avatars.githubusercontent.com/u/11835246?v=4',
 'gravatar_id': '',
 'url': 'https://api.github.com/users/DeaMariaLeon',
 'html_url': 'https://github.com/DeaMariaLeon',
 'followers_url': 'https://api.github.com/users/DeaMariaLeon/followers',
 'following_url': 'https://api.github.com/users/DeaMariaLeon/following{/other_user}',
 'gists_url': 'https://api.github.com/users/DeaMariaLeon/gists{/gist_id}',
 'starred_url': 'https://api.github.com/users/DeaMariaLeon/starred{/owner}{/repo}',
 'subscriptions_url': 'https://api.github.com/users/DeaMariaLeon/subscriptions',
 'organizations_url': 'https://api.github.com/users/DeaMariaLeon/orgs',
 'repos_url': 'https://api.github.com/users/DeaMariaLeon/repos',
 'events_url': 'https://api.github.com/users/DeaMariaLeon/events{/privacy}',
 'received_events_url': 'https://api.github.com/users/DeaMariaLeon/received_events',
 'type': 'User',
 'site_admin': False}

In [47]:

df= pd.read_excel(r'C:\Users\Naveen\Downloads\data sets\Attribute DataSet.xlsx')

In [48]:
df

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type,Recommendation
0,1006032852,Sexy,Low,4.6,M,Summer,o-neck,sleevless,empire,NaN,chiffon,ruffles,animal,1
1,1212192089,Casual,Low,0.0,L,Summer,o-neck,Petal,natural,microfiber,NaN,ruffles,animal,0
2,1190380701,vintage,High,0.0,L,Automn,o-neck,full,natural,polyster,NaN,NaN,print,0
3,966005983,Brief,Average,4.6,L,Spring,o-neck,full,natural,silk,chiffon,embroidary,print,1
4,876339541,cute,Low,4.5,M,Summer,o-neck,butterfly,natural,chiffonfabric,chiffon,bow,dot,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,713391965,Casual,Low,4.7,M,Spring,o-neck,full,natural,polyster,NaN,NaN,solid,1
496,722565148,Sexy,Low,4.3,free,Summer,o-neck,full,empire,cotton,NaN,NaN,NaN,0
497,532874347,Casual,Average,4.7,M,Summer,v-neck,full,empire,cotton,NaN,lace,solid,1
498,655464934,Casual,Average,4.6,L,winter,boat-neck,sleevless,empire,silk,broadcloth,applique,print,1
499,919930954,Casual,Low,4.4,free,Summer,v-neck,short,empire,cotton,Corduroy,lace,solid,0

# converting excel to js

In [63]:
df.to_json('converted_Excel_To_Json.json')

## pwd stands for present directory

In [62]:
pwd

'C:\\Users\\Naveen'

# storing a data

In [76]:
df= pd.read_json(r'C:\Users\Naveen\Downloads\data sets\Attribute DataSet.xlsx')

In [77]:
df

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type,Recommendation
0,1006032852,Sexy,Low,4.6,M,Summer,o-neck,sleevless,empire,None,chiffon,ruffles,animal,1
1,1212192089,Casual,Low,0.0,L,Summer,o-neck,Petal,natural,microfiber,None,ruffles,animal,0
2,1190380701,vintage,High,0.0,L,Automn,o-neck,full,natural,polyster,None,None,print,0
3,966005983,Brief,Average,4.6,L,Spring,o-neck,full,natural,silk,chiffon,embroidary,print,1
4,876339541,cute,Low,4.5,M,Summer,o-neck,butterfly,natural,chiffonfabric,chiffon,bow,dot,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,713391965,Casual,Low,4.7,M,Spring,o-neck,full,natural,polyster,None,None,solid,1
496,722565148,Sexy,Low,4.3,free,Summer,o-neck,full,empire,cotton,None,None,None,0
497,532874347,Casual,Average,4.7,M,Summer,v-neck,full,empire,cotton,None,lace,solid,1
498,655464934,Casual,Average,4.6,L,winter,boat-neck,sleevless,empire,silk,broadcloth,applique,print,1
499,919930954,Casual,Low,4.4,free,Summer,v-neck,short,empire,cotton,Corduroy,lace,solid,0

In [82]:
# this converted data is stored in the d drive
df.to_csv('E:\\converted_excel123.csv',sep= '#')

In [84]:
# this converted data is stored in the d drive and sepraating with #
df.to_csv('E:\\converted_excel123.csv',sep= '#')

In [83]:
df.to_csv('E:\\converted_excel1234.csv',sep= '#',index = False)

In [85]:
df= pd.read_excel(r'C:\Users\Naveen\Downloads\data sets\Attribute DataSet.xlsx')

ValueError: Excel file format cannot be determined, you must specify an engine manually.

In [87]:
df.to_excel(r'C:\Users\Naveen\Downloads\data sets\Attribute DataSet.xlsx')

In [89]:
df= pd.read_excel(r'C:\Users\Naveen\Downloads\data sets\Attribute DataSet.xlsx')

In [90]:
df

,Unnamed: 0,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type,Recommendation
0,0,1006032852,Sexy,Low,4.6,M,Summer,o-neck,sleevless,empire,NaN,chiffon,ruffles,animal,1
1,1,1212192089,Casual,Low,0.0,L,Summer,o-neck,Petal,natural,microfiber,NaN,ruffles,animal,0
2,2,1190380701,vintage,High,0.0,L,Automn,o-neck,full,natural,polyster,NaN,NaN,print,0
3,3,966005983,Brief,Average,4.6,L,Spring,o-neck,full,natural,silk,chiffon,embroidary,print,1
4,4,876339541,cute,Low,4.5,M,Summer,o-neck,butterfly,natural,chiffonfabric,chiffon,bow,dot,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,495,713391965,Casual,Low,4.7,M,Spring,o-neck,full,natural,polyster,NaN,NaN,solid,1
496,496,722565148,Sexy,Low,4.3,free,Summer,o-neck,full,empire,cotton,NaN,NaN,NaN,0
497,497,532874347,Casual,Average,4.7,M,Summer,v-neck,full,empire,cotton,NaN,lace,solid,1
498,498,655464934,Casual,Average,4.6,L,winter,boat-neck,sleevless,empire,silk,broadcloth,applique,print,1
499,499,919930954,Casual,Low,4.4,free,Summer,v-neck,short,empire,cotton,Corduroy,lace,solid,0